### ISSUE TITLE
我使用bugly的热更新，P的版本还是不生效

### ISSUE THREAD

**Issue by clank520** [tiann/FreeReflection#11]
使用就是 在这个方法里面调用 
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        Reflection.unseal(base);
        MultiDex.install(base);
        Beta.installTinker();

    }

**Comment by kw13630** [comment]
bugly 的applicaion 是重写之后的吧,会不会有影响

**Comment by WangYinuo** [comment]
> 使用就是 在这个方法里面调用
> protected void attachBaseContext(Context base) {
> super.attachBaseContext(base);
> Reflection.unseal(base);
> MultiDex.install(base);
> Beta.installTinker();
> 
> ```
> }
> ```

朋友 9.0上的热修复 你这里测试可用吗
