### ISSUE TITLE
对于 free_reflection:2.0.0 来说，Native 方法 unsealNative() 是否是多余的？

### ISSUE THREAD

**Issue by ZhouGongZaiShi** [tiann/FreeReflection#16]
http://weishu.me/2019/03/16/another-free-reflection-above-android-p/
在你的博客里提到了，新的方法是不需要进行内存搜索的。但目前源码里却保留着相应的 `JNI`代码。

**Comment by tiann** [comment]
的确不需要，但是可以作为一种方法供参考。

**Comment by tiann** [comment]
https://github.com/tiann/FreeReflection/commit/719b73c5effd8aadc4551d575cbc824e6746c214
