### ISSUE TITLE
在Android Q preview 4上找不到android.view.DisplayListCanvas.drawGLFunctor2 方法

### ISSUE THREAD

**Issue by lybvinci** [tiann/FreeReflection#17]
在Android Q preview 4上找不到android.view.DisplayListCanvas.drawGLFunctor2 方法。 查看官方的源码地址 https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-q-preview-4/core/java/android/view/DisplayListCanvas.java  是可以看到这个类的，能否帮忙看看是什么原因？

**Comment by tiann** [comment]
这个类中的确没有这个方法，本 lib 在 DP4上依然可以正常使用。

**Comment by lybvinci** [comment]
hi，请问哪里可以看到这个类的源码？我上面发的链接里面不是源码吗？

**Comment by tiann** [comment]
装个 preview 4的手机，把系统代码拉出来反编译看。那边不一定是最新的。

**Comment by lybvinci** [comment]
> 装个 preview 4的手机，把系统代码拉出来反编译看。那边不一定是最新的。

请问您的反编译工具是什么呀？我用dex2jar2.1 反编译说版本不符合。

**Comment by lybvinci** [comment]
能否加个联系方式，想请教一下~

**Comment by zhousysu** [comment]
请问一下android 10的framework有什么工具可以反编译吗。试了vdexExtractor反编译不了小米和华为 android 10的vdex
