### ISSUE TITLE
9.0蓝牙灰名单无法调用

### ISSUE THREAD

**Issue by liuhang1234** [tiann/FreeReflection#18]
大佬，反射调用蓝牙mac 地址时，Accessing hidden method Landroid/bluetooth/IBluetooth$Stub$Proxy;->getAddress()Ljava/lang/String; (light greylist, reflection)，另外还有 java.lang.reflect.InvocationTargetException这个异常，目前这个反射库还是无法掉起这些方法，不知道是什么原因。

**Comment by tiann** [comment]
light greylist 理论上不用这个库也能正常访问，所以肯定跟这个库没有关系。
