### ISSUE TITLE
Android 11 will prevent meta reflection

### ISSUE THREAD

**Issue by zhanghai** [tiann/FreeReflection#23]
> Apps targeting Android 11 can no longer use an extra layer of reflection to access non-SDK interfaces that are restricted.

See https://developer.android.com/preview/test-changes#prevent_meta_reflection_blacklist_access.

**Comment by tiann** [comment]
I will publish a new way to bypass it after Android 11 released.

**Comment by zhanghai** [comment]
Just curious, will the new way be Java-only or require native code?

**Comment by tiann** [comment]
It depends

**Comment by MikeoPerfect** [comment]
> It depends

six，eat gua

**Comment by s13524801** [comment]
https://github.com/ChickenHook/RestrictionBypass

**Comment by tiann** [comment]
https://github.com/tiann/FreeReflection/commit/f1a175e231bd50866e8521772b264ec58f287336

**Comment by zhangjg0201** [comment]
> > It depends
> 
> six，eat gua

wo cao, six six six

**Comment by zhangjg0201** [comment]
> Android 11
> 
> https://github.com/ChickenHook/RestrictionBypass

I find this way too. But now it has been published to github, and google is forbidding it.
[](https://android-review.googlesource.com/c/platform/art/+/1664304)
