### ISSUE TITLE
move dex code to a dedicated .dex file

### ISSUE THREAD

**Issue by samlu** [tiann/FreeReflection#28]
To directly put an encoded dex code string in code may violate Play's malicious behavior policy.

I would suggest that you don't encode the dex code, move the decoded dex bytes to a .dex file, and put it under the asset directory.

Here attached image shows you how Facebook audience network SDK does. 
It's a more safe approach for embedding the dex code in an aar file without violating Play's policy.

![fan_sdk](https://user-images.githubusercontent.com/1866938/88470119-33edfe80-cf2b-11ea-9de9-ed851362b384.png)

**Comment by tiann** [comment]
Put the dex to assets can't fit my project, but PRs are welcome.

**Comment by samlu** [comment]
ok.
