### ISSUE TITLE
where is the source code of Reflection.DEX

### ISSUE THREAD

**Issue by samlu** [tiann/FreeReflection#29]
The Reflection.DEX is a base64 encoded dex byte string. 
Would you show us the original Java source code of this dex code and how to compile it?

**Comment by tiann** [comment]
The DEX is the library itself.

**Comment by samlu** [comment]
I don't get your point. Would you explain it in more detail and list steps about how to compile to the dex code?

**Comment by tiann** [comment]
`gradle aR` to compile the project and you will get a apk, the dex is the apk.

In addition, the DEX is the Bootstrap class.

**Comment by samlu** [comment]
Got it. Thank you for supporting Android Q with a trick approach. ;-)
