### ISSUE TITLE
大佬能讲解一下用dexFile的方式绕过限制的原理吗?

### ISSUE THREAD

**Issue by jiashie** [tiann/FreeReflection#31]
看过大佬的两篇文章，理解了元反射和豁免api的方式。但为啥可以用释放一个dexFile的方式绕过限制？大佬有文章讲解一下吗？

**Comment by canyie** [comment]
系统通过检测classloader是否为null来检测该类是否是系统类，DexFile有个API可以指定这个类的classloader，弄个null上去就能过检测了

**Comment by Edison0716** [comment]
DexFile 这个类已经标记过时了。 以后恐怕有被删除的可能性。
