### ISSUE TITLE
Not work on MIUI Android 11 with target 30

### ISSUE THREAD

**Issue by drakeet** [tiann/FreeReflection#33]
Hi, recently, after upgrading my app’s targetSdkVersion to 30, this library becomes invalid for MIUI on Android 11. At least two people verified this problem. 
If the library can be updated to solve this problem will be very appreciated. Thanks!

**Comment by vvb2060** [comment]
原理上没问题，可能是内置的dex有什么地方不对？
可通过换成这个 [dex.zip](https://github.com/tiann/FreeReflection/files/6059072/dex.zip) 解决，失败时会抛出异常，示例代码：
```java
        DexFile dexFile;
        try {
            dexFile = new DexFile(code);
            Class<?> a = dexFile.loadClass("a", null);
            a.newInstance();
            dexFile.close();
        } catch (IllegalAccessException | InstantiationException | IOException ignored) {
        } catch (ExceptionInInitializerError e){
            Log.e(TAG, e.getCause().getCause().toString(), e);
        }
```

**Comment by TheMelody** [comment]
> Hi, recently, after upgrading my app’s targetSdkVersion to 30, this library becomes invalid for MIUI on Android 11. At least two people verified this problem.
> If the library can be updated to solve this problem will be very appreciated. Thanks!

目测,MIUI,android11修改了一些东西，setHiddenApiExemptions无法使用了

**Comment by vvb2060** [comment]
@TheMelody 我提供的dex能用吗？我在MIUI Android11上测试良好

**Comment by TheMelody** [comment]
> @TheMelody 我提供的dex能用吗？我在MIUI Android11上测试良好

我不会测试DEX方式的，我已经找到一个更牛逼的一个库了，刚刚测试过，完美运行，provider里面初始化，之间依赖这个库就行了：

    implementation 'com.github.ChickenHook:RestrictionBypass:2.2'

**Comment by TheMelody** [comment]
> Hi, recently, after upgrading my app’s targetSdkVersion to 30, this library becomes invalid for MIUI on Android 11. At least two people verified this problem.
> If the library can be updated to solve this problem will be very appreciated. Thanks!

纯纯写作的大佬，我找到一个更牛逼的库，我测试小窗的api都是可以使用的：


provider里面初始化，直接依赖这个库就可以了，其他的什么都不用写：

 implementation 'com.github.ChickenHook:RestrictionBypass:2.2'

**Comment by vvb2060** [comment]
这个库把简单的事情搞得太复杂……并且，要用native code的话，我更喜欢直接扫内存

**Comment by TheMelody** [comment]
> 这个库把简单的事情搞得太复杂……并且，要用native code的话，我更喜欢直接扫内存

对于我来说，太深奥了，能把事情简单话最好，我喜欢这种直接依赖的😁

**Comment by drakeet** [comment]
ChickenHook/RestrictionBypass 早就知道了，而且也知道确实对 MIUI Android 11 有效，不过我还是更喜欢 weishu 的这个库，当前这个库无法正常工作，所以我也已经同时引入 ChickenHook/RestrictionBypass 双管齐下，期待 FreeReflection 早日能够修复这个问题，这样我这边就可以去除 RestrictionBypass...

**Comment by zhanghai** [comment]
单从实现来说，FreeReflection 的这个 unsealByDexFile 会导致每次应用冷启动时都要对一个小的 DEX 文件进行 I/O，所以感觉相比之下还是 ChickenHook/RestrictionBypass 的在 native 创建新线程来获取空堆栈更加轻量一些。FreeReflection 的 unsealNative 是第三种方法，但需要写死一些偏移量 + 动态查找内存内容，我觉得比起前两种使用 API 的方法来说还是危险很多的。

**Comment by drakeet** [comment]
@zhanghai 我测试了二者在冷启动时的性能，都是接近 0 毫秒级的，不知道极端情况下是否有较大差异。但 ChickenHook/RestrictionBypass 有一个缺点就是 so 文件很大，单份 so 文件未压缩之前有上百 KB，因此对安装包体积会有些影响🤔

**Comment by zhanghai** [comment]
ChickenHook/RestrictionBypass 大的原因不知道是不是因为用了 C++（std::async）。如果我自用的话我打算用 C + pthread 重写下。然后因为 Material Files 已经有原生库了所以不太在意多一个函数 😅

**Comment by Kola-Chao** [comment]
mark一下

**Comment by galian123** [comment]
> Hi, recently, after upgrading my app’s targetSdkVersion to 30, this library becomes invalid for MIUI on Android 11. At least two people verified this problem.
> If the library can be updated to solve this problem will be very appreciated. Thanks!

me too.

**Comment by AriaLyy** [comment]
mark 一下，我也有这个问题，应该是小米自己改了一些东西

**Comment by vvb2060** [comment]
https://github.com/LSPosed/AndroidHiddenApiBypass 现在我推荐这个库

**Comment by zhanghai** [comment]
据说 不需要新开 thread，直接在 JNI_OnLoad 里设置 exemption 也可以成功绕过

**Comment by tiann** [comment]
https://github.com/tiann/FreeReflection/commit/9bc252dd65372c621a0db1455f5e5be5c9e73d45

**Comment by zhangjg0201** [comment]
> > @TheMelody 我提供的dex能用吗？我在MIUI Android11上测试良好
> 
> 我不会测试DEX方式的，我已经找到一个更牛逼的一个库了，刚刚测试过，完美运行，provider里面初始化，直接依赖这个库就行了：
> 
> ```
> implementation 'com.github.ChickenHook:RestrictionBypass:2.2'
> ```

谷歌已经开始封了
[](https://android-review.googlesource.com/c/platform/art/+/1664304)

**Comment by zhangjg0201** [comment]
> ChickenHook/RestrictionBypass 大的原因不知道是不是因为用了 C++（`std::async`），如果我自用的话我打算用 C + pthread 重写下；当然也可能原生库有一些基础体积需求。但在我的项目里因为 Material Files 已经有原生库了所以不太在意多一个函数

重写下就好。这个库确实有点复杂了。

**Comment by zhangjg0201** [comment]
> https://github.com/LSPosed/AndroidHiddenApiBypass 现在我推荐这个库

现在这个库还能用吗？ 他用的是java.lang.invoke.MethodHandle。从android 11的源码来看会被封。

`struct FirstExternalCallerVisitor : public StackVisitor {
    explicit FirstExternalCallerVisitor(Thread* thread)
        : StackVisitor(thread, nullptr, StackVisitor::StackWalkKind::kIncludeInlinedFrames),
          caller(nullptr) {
    }

    bool VisitFrame() override REQUIRES_SHARED(Locks::mutator_lock_) {
      ArtMethod *m = GetMethod();
      if (m == nullptr) {
        // Attached native thread. Assume this is *not* boot class path.
        caller = nullptr;
        return false;
      } else if (m->IsRuntimeMethod()) {
        // Internal runtime method, continue walking the stack.
        return true;
      }

      ObjPtr<mirror::Class> declaring_class = m->GetDeclaringClass();
      if (declaring_class->IsBootStrapClassLoaded()) {
        if (declaring_class->IsClassClass()) {
          return true;
        }
        // Check classes in the java.lang.invoke package. At the time of writing, the
        // classes of interest are MethodHandles and MethodHandles.Lookup, but this
        // is subject to change so conservatively cover the entire package.
        // NB Static initializers within java.lang.invoke are permitted and do not
        // need further stack inspection.
        ObjPtr<mirror::Class> lookup_class = GetClassRoot<mirror::MethodHandlesLookup>();
        if ((declaring_class == lookup_class || declaring_class->IsInSamePackage(lookup_class))
            && !m->IsClassInitializer()) {
          return true;
        }
        // Check for classes in the java.lang.reflect package, except for java.lang.reflect.Proxy.
        // java.lang.reflect.Proxy does its own hidden api checks (https://r.android.com/915496),
        // and walking over this frame would cause a null pointer dereference
        // (e.g. in 691-hiddenapi-proxy).
        ObjPtr<mirror::Class> proxy_class = GetClassRoot<mirror::Proxy>();
        if (declaring_class->IsInSamePackage(proxy_class) && declaring_class != proxy_class) {
          if (Runtime::Current()->isChangeEnabled(kPreventMetaReflectionBlacklistAccess)) {
            return true;
          }
        }
      }

      caller = m;
      return false;
    }
`

**Comment by vvb2060** [comment]
@zhangjg0201   那么你认为，从源码来看，直接在原生代码的 JNI_OnLoad 处调用 setHiddenApiExemptions 有没有被封呢 (

**Comment by zhangjg0201** [comment]
> @zhangjg0201 那么你认为，从源码来看，直接在原生代码的 JNI_OnLoad 处调用 setHiddenApiExemptions 有没有被封呢 (

如果这个代码上去应该就会被封

[https://android-review.googlesource.com/c/platform/art/+/1664304](https://android-review.googlesource.com/c/platform/art/+/1664304)

**Comment by yujincheng08** [comment]
这是 PR，还没 merge，你说呢。而且这代码还是我们提交的。

> 如果这个代码上去应该就会被封
> 
> https://android-review.googlesource.com/c/platform/art/+/1664304

**Comment by zhangjg0201** [comment]
> 这是 PR，还没 merge，你说呢。而且这代码还是我们提交的。
> 
> > 如果这个代码上去应该就会被封
> > https://android-review.googlesource.com/c/platform/art/+/1664304

看样子已经过了presubmit。估计android 12能merge吧。

没搞明白啊，为什么一边需要调用隐藏api,一边给google提pr ? 你们是google员工？

**Comment by zhanghai** [comment]
不要乱猜，Android 12 里极大概率不会有这个 change。

**Comment by MuntashirAkon** [comment]
> 不要乱猜，Android 12 里极大概率不会有这个 change。

Or it won't be merged at all.

**Comment by CaMnter** [comment]
> > 这是 PR，还没 merge，你说呢。而且这代码还是我们提交的。
> > > 如果这个代码上去应该就会被封
> > > https://android-review.googlesource.com/c/platform/art/+/1664304
> 
> 看样子已经过了presubmit。估计android 12能merge吧。
> 
> 没搞明白啊，为什么一边需要调用隐藏api,一边给google提pr ? 你们是google员工？

显而易见，损人利己，把市场上大多方案都堵了，只要自己的方案 OK 就行
