### ISSUE TITLE
Consider publishing the lib to jitpack

### ISSUE THREAD

**Issue by ignoramous** [tiann/FreeReflection#34]
...so that builds could be verified (useful for apps on F-Droid).

Jitpack is pretty straight forward.

Docs: https://jitpack.io/docs/BUILDING

Ex (custom builds): https://github.com/celzero/firestack/blob/e62f1dd5/jitpack.yml

**Comment by tiann** [comment]
https://jitpack.io/#tiann/FreeReflection/3.1.0
