### ISSUE TITLE
Please considering update package to the Maven Central

### ISSUE THREAD

**Issue by wrlu** [tiann/FreeReflection#35]
JCenter have already became a read-only repository on March 31st, 2021.  Please considering update package to the Maven Central. For more info please visit: [https://developer.android.com/studio/build/jcenter-migration](https://developer.android.com/studio/build/jcenter-migration)
When using mavenCentral() I got this error: 
```
Failed to resolve: me.weishu:free_reflection:3.0.1
```

**Comment by tiann** [comment]
https://jitpack.io/#tiann/FreeReflection/3.1.0
