### ISSUE TITLE
查了下AOSP最新的代码，漏洞应该还没有修复，理论上依然支持Android 12

### ISSUE THREAD

**Issue by MegatronKing** [tiann/FreeReflection#44]
通过将classloader设置为null来提高dex中api执行的domain级别，真是机智，佩服！
依然支持Android S，建议作者改下README!

**Comment by yangcyzhang** [comment]
> 
确认支持Android S吗，我试了targetSdkVersion 31运行不过a

**Comment by icanly** [comment]
targetSdkVersion 30 ，就不行了

**Comment by StephenGiant** [comment]
11下挂了 https://github.com/android-notes/SwissArmyKnife 这个库就是例子
