### ISSUE TITLE
请问能否调用com.android.server 下面的class？

### ISSUE THREAD

**Issue by FOaker** [tiann/FreeReflection#46]
![image](https://user-images.githubusercontent.com/70738721/156098701-e38e33ee-c8c3-42d3-af3a-b509fc4969b7.png)

找不到class
有没有方法可以调用呢？
大佬救命

**Comment by canyie** [comment]
需要手动加载 system server 的 classpath，普通 app 里不加载 system server 的 dex。

**Comment by FOaker** [comment]
> 

请问如何手动加载system server 的 classpath呢？

**Comment by FOaker** [comment]
> 需要手动加载 system server 的 classpath，普通 app 里不加载 system server 的 dex。

请问如何手动加载system server 的 classpath呢？

**Comment by LiuXinyi** [comment]
你这个思路错了，比如你最终是想调用BluetoothManagerService的代码，这个是在系统层的，，
客户端(App)是通过IPC调用过去的，所以，你要去查系统源码，看BluetoothManagerService#xxx 函数，是由那个客户端函数通过IPC调用的，然后反射此客户端函数，间接调用

**Comment by LiuXinyi** [comment]
http://aosp.opersys.com/xref/android-12.0.0_r2/xref/frameworks/base/services/core/java/com/android/server/BluetoothManagerService.java
