### ISSUE TITLE
反射vivo系统方法异常

### ISSUE THREAD

**Issue by haohao123456** [tiann/FreeReflection#53]
vivo x23，funtouchOS10，android 9

Class<?> shortcutList = Class.forName("com.bbk.launcher2.installshortcut.PurviewActivity");
异常报类找不到，
我用adb查看activity，是有这个类的
adb shell "dumpsys window | grep mCurrentFocus"
mCurrentFocus=Window{b3629ee u0 com.bbk.launcher2/com.bbk.launcher2.installshortcut.PurviewActivity}

**Comment by su1216** [comment]
这个类是launcher的，当然拿不到

**Comment by haohao123456** [comment]
哦，这块我不了解
我之前遇到华为的反射找不到类，加上FreeReflection框架就能拿到类了
Class<?> PermissionManager = Class.forName("com.huawei.hsm.permission.PermissionManager");
所以，习惯性的以为，所有的类，都可以反射
我的目的是为了获取到vivo手机 创建桌面快捷方式的权限（是允许或是禁止）
github上好些这种方式获取vivo的桌面权限是否开启
 public static int checkOnVIVO(@NonNull Context context) {
        ContentResolver contentResolver = context.getContentResolver();
        if (contentResolver == null) {
            return PERMISSION_UNKNOWN;
        }
        Cursor query = null;
        try {
            Uri parse = Uri.parse("content://com.bbk.launcher2.settings/favorites");
            query = contentResolver.query(parse, null, null, null, null);
            if (query == null) {
                return PERMISSION_UNKNOWN;
            }
            while (query.moveToNext()) {
                String titleByQueryLauncher = query.getString(query.getColumnIndexOrThrow("title"));
                if (!TextUtils.isEmpty(titleByQueryLauncher)) {
                    int value = query.getInt(query.getColumnIndexOrThrow("shortcutPermission"));
                    if (value == 1 || value == 17) {
                        return PERMISSION_DENIED;
                    } else if (value == 16) {
                        return PERMISSION_GRANTED;
                    } else if (value == 18) {
                        return PERMISSION_ASK;
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (query != null) {
                query.close();
            }
        }
        return PERMISSION_UNKNOWN;
    }
   但是报错
   		java.lang.SecurityException: Permission Denial:
		opening provider com.bbk.launcher2.data.LauncherProvider from ProcessRecord{) 
		requires com.bbk.launcher2.permission.READ_SETTINGS or com.bbk.launcher2.permission.WRITE_SETTINGS
		
    添加权限或则用反射都走不通，
    （参考这个博客，https://hjw45611.github.io/blog/2021/06/22/Vivo%E5%88%9B%E5%BB%BA%E6%A1%8C%E9%9D%A2%E5%BF%AB%E6%8D%B7%E6%96%B9%E5%BC%8F/
    不知道他怎么拿到权限的，就想着反射系统类试试）
    关于获取vivo桌面快捷方式权限，大佬有什么建议吗？
